### ISSUE TITLE
[BUG] Leaking information about existing users

### ISSUE THREAD

**Issue by derlin** [sventorben/keycloak-home-idp-discovery#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behaviour makes it easy to discover which email exists in Keycloak.

When this SPI is set up correctly, the first login screen only shows an email field. If you enter an email and press enter, what should happen is:

1. the email domain matches a configured IDP -> the user gets redirected to the IDP (all good)
2. the email doesn't match a configured IDP. In this case, a new form appears asking you for a password.

The problem arises in the use-case number (2). If you enter a **valid email** (*case a*), that is an email that matches a user in the system, you get this view:
<img width="542" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/5463445/c7dbbeee-cc55-4916-9890-0b887d3c129d">

But if you enter an **unknown email** (*case b*), something that doesn't match any user in the system, the view is different:

<img width="591" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/5463445/d5304213-4ae9-42f8-95f1-6f3e682e9299">

This makes it easy for attackers to discover the registered emails present on keycloak.

### Expected Behavior

Ideally, *case a* should be the expected behaviour, whether the user exists on the system or not.

I believe the problem is introduced with the line https://github.com/sventorben/keycloak-home-idp-discovery/blob/main/src/main/java/de/sventorben/keycloak/authentication/hidpd/HomeIdpDiscoveryAuthenticator.java#L115 (`context.setUser`).

### Steps To Reproduce

Setup:

1. Add the home-idp-discovery spi
2. copy the builtin browser flow, and add the "*Home Idp Discovery*" before the "browser forms": 
<img width="1512" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/5463445/7bb5d077-2545-4dd9-814a-57c3cfb0c1ca">
3. bind the new flow to the browser flow
4. configure one or more idps by setting the `idp.alias` attribut to a domain, for example `aa.com`

Now, try to login to keycloak using the `keycloak` theme, once with a valid email, once with a random one.

### Version

```markdown
- Keycloak: 22.0.4
- This extension: 22.0.0
```

**Comment by sventorben** [comment]
Hello @derlin!

Thanks for reporting this! Give me some time to investigate this a litte deeper, because I think the main cause for this issue may be with Keycloak itself.
The issue that you describe is due to a functionality in the `UsernamePasswordForm`: https://github.com/keycloak/keycloak/blob/22.0.4/services/src/main/java/org/keycloak/authentication/authenticators/browser/UsernamePasswordForm.java#L67

Basically the same issue arises when I configure a flow like this without any extensions used:

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12183470/f3491d32-fd14-42ea-ba46-8f61428aa4b5)


For a non-existing user this results in the following:
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12183470/b9dc028b-e210-48e3-837d-4553d299e8bb)

If the user exists, the result is this:

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12183470/b7d3ed2f-9577-4752-9bba-aeede5ce4c12)

So, I think this is more a general issue with Keycloak's `UsernamePasswordForm` authenticator.

Any thoughts on this?

Best regards
Sven-Torben

**Comment by derlin** [comment]
First, thank you for this fast reply, it is highly appreciated :)

I agree this mechanism is found on Keycloak, but I still believe the bug comes from this SPI.

If I read the code properly, the keycloak forms (username or username/password forms) are quite generic and used in different context. In the regular auth flow, `context.setUser()` is never called, so there is no leak. And using a username form right before a username/password form (like in your example) is not a "standard" or meaningful auth flow. I believe this user context was initially thought to be used in the reset email or reset password actions (among other), when the force reauthenticate flag is set. In this context, you already have a session/user, and just want to display the login form again. It may also be used after a registration with a provider, to set credentials. Long story short, `context.setUser` doesn't seem to be used prior to an authentication (or existing session) in the keycloak code.

I would say the best would be to either clear the user from the context (as done in my PR) or not set the context at all.

**Comment by sventorben** [comment]
Thanks for your feedback here! I'd rather prefer not to set the user in the context then. 

I have prepared a PR and added some test cases to ensure we are safe here in the future. 

Thanks again for the report, your time and efforts you put into this.

**Comment by sventorben** [comment]
Here you go: https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v22.1.0
