### ISSUE TITLE
[Feature] Add a way to redirect the user by submitting email from keycloak rest api 

### ISSUE THREAD

**Issue by cellezam** [sventorben/keycloak-home-idp-discovery#345]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

We have to pass by the keycloak form for having the flow works.

### Describe the solution you'd like

I would like to be able to use the rest api, submit the email and get the configured identity provider with the domain.

### Describe alternatives you've considered

There is no alternatives that i see. Only the keycloak login form.

**Comment by sventorben** [comment]
Thank you for reaching out with your feature request. I appreciate your interest in enhancing the functionality of this Keycloak extension.

At present, the primary focus of this extension is to augment the native capabilities of Keycloak itself rather than integrating with third-party applications. Given this direction, it seems that the feature you're suggesting might be more effectively implemented directly within your own application.

That said, I'm grateful for your input, as it helps us explore potential areas of expansion and better understand the needs of the users.

Best,
Sven-Torben

**Comment by cellezam** [comment]
Yes previously i was doing a keycloak integration by generating a url and make usage of idp_hint in the query params.
But it was not suitable as i had to configured on my own backend the identity provider to redirect.

You made a great work with this plugin ! Very easy to integrate and straightforward to use.
