### ISSUE TITLE
[BUG] Unable to redirect to Organization IDP when login

### ISSUE THREAD

**Issue by HanifAbRazak** [sventorben/keycloak-home-idp-discovery#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. I created a flow where only have cookie and Home IDP Discovery - Organization via Email.
2. Added new IDP with alias OIDC
3. I created user named "test "and email "user@test.io"
4. I created organization name "Test" and assign domain "test.io"
5. Add "test" as member of "Test" organization
6. Linked "OICD" IDP to "Test" organization
7. Try to login with link "<host>/realms/test/account/"
8. enter email "user@test.io" and click "Sign in"

Result : "Invalid username or password"

Please advice. Did I missed anything?

### Expected Behavior

upon clicking sign in, Keycloak will redirect to the IDP that has been set to the organization

### Steps To Reproduce

![Screenshot 2024-07-11 161209](https://github.com/sventorben/keycloak-home-idp-discovery/assets/142989669/2b8e7c70-7664-4315-830f-79625a15a4c5)
![Screenshot 2024-07-11 161222](https://github.com/sventorben/keycloak-home-idp-discovery/assets/142989669/b6b98224-20cb-44b3-aa18-9b3b9402f26c)
![Screenshot 2024-07-11 162204](https://github.com/sventorben/keycloak-home-idp-discovery/assets/142989669/fbf8bdff-2588-47c1-85b3-34e1eca5d133)
![Screenshot 2024-07-11 161447](https://github.com/sventorben/keycloak-home-idp-discovery/assets/142989669/bf496909-a616-4504-aa5a-b56755c96df4)

![Screenshot 2024-07-11 161431](https://github.com/sventorben/keycloak-home-idp-discovery/assets/142989669/d823cea0-1c04-4097-895a-fed1fc1f0db7)
![Screenshot 2024-07-11 161130](https://github.com/sventorben/keycloak-home-idp-discovery/assets/142989669/83dd8601-8ee1-445a-96ed-2246db32bb1f)

### Version

```markdown
- Keycloak:25.0.0
- This extension:
```

**Comment by sventorben** [comment]
Hey @HanifAbRazak,

that's an interesting find.
The extension validates whether a domain is marked as "verified" and only redirects users to an associated IdP if that is the case.
However, while the KC internal model has a property to check verification status, I cannot find a way to set that status via the Keycloak UI. It can be set via REST/HTTP request though.

As this feature is early preview, I would like to understand why you are using this extension instead of the built-in KC functionality for your usecase. Could you elaborate that a bit, please?

Best,
Sven-Torben

**Comment by sventorben** [comment]
I haven’t received any feedback or updates on this issue for a while. To keep the issue tracker clean and focused, I am closing this issue for now.

If you still face the problem or have additional information to provide, feel free to reopen the issue or create a new one.

Thank you for your understanding!
